### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by fentesalexj** [wiktor-kudla/cradle-im#2]
Win version
Activation does not work through a signal-cli
when synchronization with contacts begins immediately writes an error

Something went wrong

**Comment by wiktor-kudla** [comment]
Hi dear user fentesalexj,

We have been made aware that in the last week, Signal has reverted their API v1 REST endpoints on their server. We are working to integrate the registration service into Cradle, but at the moment we are sitting on Signal. Within the next week you can expect the new commit to resolve the API v1 registration bug.

Thank you for bringing it to my attention & happy new year,
Wiktor Kudla

**Comment by fentesalexj** [comment]
good day
Orient for time please when you plan to fix registration

**Comment by fentesalexj** [comment]
good day
Orient for time please when you plan to fix registration
